docs:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - README.md
      - all-globs-to-all-files:
        - '!src/**'
        - '!pyproject.toml'

internal:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - .github/**
        - scripts/**
        - .gitignore
        - .pre-commit-config.yaml
        - pdm_build.py
        - requirements*.txt
        - uv.lock
      - all-globs-to-all-files:
        - '!README.md'
        - '!src/**'
        - '!pyproject.toml'
